const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGNIN_START: "GOOGLE_SIGNIN_START",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FALIURE: "SIGNIN_FALIURE",
  EMAIL_SIGNIN_START: "EMAIL_SIGNIN_START",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGNOUT_START: "SIGNOUT_START",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FALIURE: "SIGNOUT_FALIURE",
  SIGNUP_START: "SIGNUP_START",
  SIGNUP_FALIURE: "SIGNUP_FALIURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
};

export default userActionTypes;
